# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

#    volumes:
#      - ./data:/var/lib/postgresql/data



#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080